mqtt_username=Mqtt
mqtt_password=lolENGEN12
#Your Relay ID
mqtt_clientid=Relay_01
mqtt_topic_prefix=Relay_01
#MQTT server address
mqtt_address=tcp://192.168.86.32:1883
screen_timeout=20
proximity_threshold=5500
hide_status_bar=true
#Button/Switch State
relay_upper_flags=3
relay_lower_flags=3
send_proximity_trigger=true
send_screen_state=true
debug=true
#log_file=/data/local/tmp/wink_manager.log